### ISSUE TITLE
myoms 里的model是 你是不是有省略了代码？

### ISSUE THREAD

**Issue by nanzhushan** [jwh5566/my_oms#1]
myoms 里的model是 你是不是有省略了代码？

**Comment by jwh5566** [comment]
model 是在asset app的model里面

**Comment by nanzhushan** [comment]
python manage.py makemigrations
提示：
django.db.utils.OperationalError: (1049, "Unknown database 'oms'")

settings.py和settings_local.py  都是正确的，oms库是有的

**Comment by nanzhushan** [comment]
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST':'192.168.30.143',
        'NAME': 'oms',
        'USER': 'root',
        'PORT': 3306,
        'PASSWORD': 'root',
    }
}

奇怪 用localhost 就可以 用其他的就不行
