### ISSUE TITLE
增加 修改数据报错

### ISSUE THREAD

**Issue by trockxi** [jwh5566/my_oms#3]
![image](https://user-images.githubusercontent.com/28647418/34375797-592b83a0-eb23-11e7-8f1d-100a151aee1c.png)

![image](https://user-images.githubusercontent.com/28647418/34375806-6badb124-eb23-11e7-894b-5ecd4a034739.png)
不知道原因，请指教。

**Comment by jwh5566** [comment]
从你上面的报错看 应该是action_ip这个字段的信息 超过15个字符了

**Comment by trockxi** [comment]
![image](https://user-images.githubusercontent.com/28647418/34375983-56d4a5ae-eb24-11e7-927a-06461cbe32a7.png)

这没15个字符吧  IP

**Comment by trockxi** [comment]
是我没算  是超过字符了 
alter table asset_message modify action_ip  varchar(30);
改了就好了

**Comment by trockxi** [comment]
话说这个要在部署里面的要修正一下了  字符长度小了

**Comment by trockxi** [comment]
还有 创建数据库那里 也需要指定一下字符集 不然也会报错

**Comment by jwh5566** [comment]
嗯 好的  我知道了 谢谢指出
